[video_pis]
# Raspberry Pi hosts for channels 14 through 33.
# Hostnames follow the format: raspichanelXX.yess

raspichanel14.yess media_folder=14_Movie
raspichanel15.yess media_folder=15_Music
raspichanel16.yess media_folder=16_SoftCore
raspichanel17.yess media_folder=17_PMV
raspichanel18.yess media_folder=18_Mofos
raspichanel19.yess media_folder=19_Blowjob
#raspichanel20.yess media_folder=20_HighProduction
#raspichanel21.yess media_folder=21_Lesbian
#raspichanel22.yess media_folder=22_Gay
raspichanel23.yess media_folder=23_Trans
raspichanel24.yess media_folder=24_Anal
raspichanel25.yess media_folder=25_Hentai
raspichanel26.yess media_folder=26_ForHer
raspichanel27.yess media_folder=27_BDSM
raspichanel28.yess media_folder=28_Milf
raspichanel29.yess media_folder=29_Teen
raspichanel30.yess media_folder=30_Asian
raspichanel31.yess media_folder=31_Latina
raspichanel32.yess media_folder=32.1_Russian720p
# raspichanel33.yess media_folder=33_FOLDER_NAME
