[video_pis]
# Raspberry Pi hosts for channel 14 through channel 33
# Hostnames follow the example format: pi@raspichanelXX.yess

raspichanel14.yess nas_source_path=/home/tony/Desktop/pivideotest/14_Movie
raspichanel15.yess nas_source_path=/home/tony/Desktop/pivideotest/15_Music
raspichanel16.yess nas_source_path=/home/tony/Desktop/pivideotest/16_SoftCore
raspichanel17.yess nas_source_path=/home/tony/Desktop/pivideotest/17_PMV
raspichanel18.yess nas_source_path=/home/tony/Desktop/pivideotest/18_Mofos
raspichanel19.yess nas_source_path=/home/tony/Desktop/pivideotest/19_Blowjob
#raspichanel20.yess ansible_user=pi usb only
#raspichanel21.yess ansible_user=pi usb only
#raspichanel22.yess ansible_user=pi usb only
#raspichanel23.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/23
#raspichanel24.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/24
#raspichanel25.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/25
#raspichanel26.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/26
#raspichanel27.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/27
#raspichanel28.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/28
#raspichanel29.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/29
#raspichanel30.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/30
#raspichanel31.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/31
#raspichanel32.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/32
#raspichanel33.yess nas_source_path=/mnt/rootFolder/data/media/youtube-dl/33

[video_pis:vars]
ansible_user=pi
ansible_password=video
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
